<a href="https://colab.research.google.com/github/reshmalik-prog/231A031-NLP-Lab/blob/main/Expp_8_NLP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Using word2vec

In [24]:
print("Malik Reshma 231A031")

documents = [

"Machine learning enables computers to learn from data.",
"Computers can learn patterns from data using machine learning.",
"Natural language processing helps computers understand human language.",
"The football team won the match yesterday.",
"Deep learning is a branch of machine learning."

]

Malik Reshma 231A031

In [3]:
print("Malik Reshma 231A031")


from sklearn. feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
import pandas as pd

Malik Reshma 231A031

In [5]:

for i, document in enumerate(documents):
  print(f"D{i+1}: {document}")

D1: Machine learning enables computers to learn from data.
D2: Computers can learn patterns from data using machine learning.
D3: Natural language processing helps computers understand human language.
D4: The football team won the match yesterday.
D5: Deep learning is a branch of machine learning.

In [8]:
print("Malik Reshma 231A031")

vectorizer = TfidfVectorizer(stop_words='english')

tfidf_matrix = vectorizer.fit_transform(documents)

print(tfidf_matrix.shape)

#(5,21) -> 5 rows,

Malik Reshma 231A031
(5, 21)

In [16]:
print("Malik Reshma 231A031")
tfidf_df = pd.DataFrame(
  tfidf_matrix.toarray(),
  columns=vectorizer.get_feature_names_out(),
  index=["D1", "D2", "D3", "D4", "D5"]
)
tfidf_df.round(2)

Malik Reshma 231A031

,branch,computers,data,deep,enables,football,helps,human,language,learn,...,machine,match,natural,patterns,processing,team,understand,using,won,yesterday
D1,0.00,0.35,0.42,0.00,0.52,0.00,0.00,0.00,0.00,0.42,...,0.35,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
D2,0.00,0.31,0.37,0.00,0.00,0.00,0.00,0.00,0.00,0.37,...,0.31,0.00,0.00,0.46,0.00,0.00,0.00,0.46,0.00,0.00
D3,0.00,0.22,0.00,0.00,0.00,0.00,0.33,0.33,0.65,0.00,...,0.00,0.00,0.33,0.00,0.33,0.00,0.33,0.00,0.00,0.00
D4,0.00,0.00,0.00,0.00,0.00,0.45,0.00,0.00,0.00,0.00,...,0.00,0.45,0.00,0.00,0.00,0.45,0.00,0.00,0.45,0.45
D5,0.49,0.00,0.00,0.49,0.00,0.00,0.00,0.00,0.00,0.00,...,0.33,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00

In [14]:
tfidf_df

,branch,computers,data,deep,enables,football,helps,human,language,learn,...,machine,match,natural,patterns,processing,team,understand,using,won,yesterday
D1,0.000000,0.350669,0.422447,0.000000,0.523612,0.000000,0.000000,0.000000,0.000000,0.422447,...,0.350669,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000
D2,0.000000,0.310659,0.374247,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.374247,...,0.310659,0.000000,0.000000,0.46387,0.000000,0.000000,0.000000,0.46387,0.000000,0.000000
D3,0.000000,0.217874,0.000000,0.000000,0.000000,0.000000,0.325326,0.325326,0.650651,0.000000,...,0.000000,0.000000,0.325326,0.00000,0.325326,0.000000,0.325326,0.00000,0.000000,0.000000
D4,0.000000,0.000000,0.000000,0.000000,0.000000,0.447214,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.447214,0.000000,0.00000,0.000000,0.447214,0.000000,0.00000,0.447214,0.447214
D5,0.485496,0.000000,0.000000,0.485496,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.325142,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000

In [17]:
print("Malik Reshma 231A031")
print(tfidf_matrix)

Malik Reshma 231A031
<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 29 stored elements and shape (5, 21)>
  Coords	Values
  (0, 11)	0.3506693043291627
  (0, 10)	0.3506693043291627
  (0, 4)	0.5236123665243221
  (0, 1)	0.3506693043291627
  (0, 9)	0.4224471603802672
  (0, 2)	0.4224471603802672
  (1, 11)	0.3106590996907812
  (1, 10)	0.3106590996907812
  (1, 1)	0.3106590996907812
  (1, 9)	0.3742473404158369
  (1, 2)	0.3742473404158369
  (1, 14)	0.46386993205061533
  (1, 18)	0.46386993205061533
  (2, 1)	0.2178743518668476
  (2, 13)	0.3253256089927616
  (2, 8)	0.6506512179855232
  (2, 15)	0.3253256089927616
  (2, 6)	0.3253256089927616
  (2, 17)	0.3253256089927616
  (2, 7)	0.3253256089927616
  (3, 5)	0.4472135954999579
  (3, 16)	0.4472135954999579
  (3, 19)	0.4472135954999579
  (3, 12)	0.4472135954999579
  (3, 20)	0.4472135954999579
  (4, 11)	0.32514226376056643
  (4, 10)	0.6502845275211329
  (4, 3)	0.4854959019308356
  (4, 0)	0.4854959019308356

In [13]:
pd.DataFrame()

Empty DataFrame
Columns: []
Index: []

In [18]:
print("Malik Reshma 231A031")
print(vectorizer.get_feature_names_out())

Malik Reshma 231A031
['branch' 'computers' 'data' 'deep' 'enables' 'football' 'helps' 'human'
 'language' 'learn' 'learning' 'machine' 'match' 'natural' 'patterns'
 'processing' 'team' 'understand' 'using' 'won' 'yesterday']

In [19]:
similarity_matrix = cosine_similarity(tfidf_matrix)

similarity_matrix

array([[1.        , 0.64301528, 0.07640185, 0.        , 0.34205223],
       [0.64301528, 1.        , 0.06768465, 0.        , 0.30302521],
       [0.07640185, 0.06768465, 1.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 1.        , 0.        ],
       [0.34205223, 0.30302521, 0.        , 0.        , 1.        ]])

In [21]:
print("Malik Reshma 231A031")
similarity_df = pd.DataFrame(
  similarity_matrix,
  index=["D1", "D2", "D3", "D4", "D5"],
  columns=["D1", "D2", "D3", "D4", "D5"]

)
similarity_df.round(3)

Malik Reshma 231A031

       D1     D2     D3   D4     D5
D1  1.000  0.643  0.076  0.0  0.342
D2  0.643  1.000  0.068  0.0  0.303
D3  0.076  0.068  1.000  0.0  0.000
D4  0.000  0.000  0.000  1.0  0.000
D5  0.342  0.303  0.000  0.0  1.000

Task: Create a function based on this vocabulary to find similarity between two documents

In [26]:
print("Malik Reshma 231A031")

def similar(D1,D2):
  vector=vectorizer.fit_transform([D1,D2])
  similarity=cosine_similarity(vector)
  return similarity

Malik Reshma 231A031

In [27]:
print("Malik Reshma 231A031")

D7="Deep studying is important and very easy to learn"
D8="Machine learning is a useful branch of computer engineering"
similar(D7,D8)

Malik Reshma 231A031

array([[1., 0.],
       [0., 1.]])

In [29]:
print("Malik Reshma 231A031")
highest_similarity = -1
most_similar_pair = None

for i in range(len(documents)):
  for j in range(i + 1, len(documents)):

    similarity = similarity_matrix[i][j]

    if similarity > highest_similarity:
      highest_simlarity = similarity
      most_similar_pair = (i, j)

print(f"Most similar documents:")
print(f"D{most_similar_pair[0]+1} and D{most_similar_pair[1]+1}")

print(f"Similarity: {highest_similarity :.3f}")

Malik Reshma 231A031
Most similar documents:
D4 and D5
Similarity: -1.000

In [30]:
print("Malik Reshma 231A031")
print(f"D{most_similar_pair[0]+1}: {documents[most_similar_pair[0]]}")
print(f"D{most_similar_pair[1]+1}: {documents[most_similar_pair[1]]}")

Malik Reshma 231A031
D4: The football team won the match yesterday.
D5: Deep learning is a branch of machine learning.